### ISSUE TITLE
iPhone problem

### ISSUE THREAD

**Issue by timrobinson81** [graphicore/librebarcode#29]
Hi everyone,
Hope you're all well.
If you look at this link below on an iPhone, 'Libre Barcode EAN13 Text' on Google Fonts renders only numbers and doesn't appear like a bar-code as it does on other devices: 
https://bit.ly/2TUo3Tp
Many thanks and kind regards,
Tim

**Comment by graphicore** [comment]
Hi, I can reproduce this, but, I don't think it's a problem with the font, as I can use the fonts on iOS (13.7) Safari (NOTE: font version is 1.006, newer than the one currently at google fonts):

[ean13-testing page](https://graphicore.github.io/librebarcode/documentation/ean13-testing) screenshot from IPhone.

![IMG_5164](https://user-images.githubusercontent.com/393132/101718956-97279a00-3aa2-11eb-80d5-0d140bff3a77.PNG)

This lead to a strange finding though. May not be the case for the current version 1.004 now on Google Fonts, as I am using v1.006 which is *not yet* updated there!: 

The complex symbol selection of the font is done using OpenType Feature substitutions, namely the `calt` feature, which should be on by default, according to the spec. In this font, with `calt` turned off you don't get numbers but patterns of `number below + start pattern`. That is because it supports a compatible input encoding mode, compatible with the [grandzebu EAN 13 font](https://grandzebu.net/informatique/codbar-en/ean13.htm):

```css
/* CSS */
.ean13 {
    font-family: "Libre Barcode EAN13 Text";
    font-feature-settings: "calt" 0;
}
```

![IMG_5165](https://user-images.githubusercontent.com/393132/101720362-b70c8d00-3aa5-11eb-8aa2-63cb98af6fd3.PNG)

When `calt` is on, an input like that will be turned into an barcode. The first `calt` feature turns all compatibility glyphs into number glyphs and from there continues. With iOS on Safari and Chrome it applies just the first `calt` rule then stops.

```css
/* CSS */
.ean13 {
    font-family: "Libre Barcode EAN13 Text";
}
```

![IMG_5166](https://user-images.githubusercontent.com/393132/101720771-b7f1ee80-3aa6-11eb-9c4d-092086da1cc2.PNG)

In CSS, using "font-feature-settings: "calt" 1;" fixes it!

```css
/* CSS */
.ean13 {
    font-family: "Libre Barcode EAN13 Text";
    font-feature-settings: "calt" 1;
}
```

Using `font-feature-settings: "calt" 0;` turnes `calt` off as expected.

So there's apparently a *third mode* in iOS, one **between on and off**. 🤬

I suggest waiting for the update at Google Fonts to version 1.006 before reporting there. But eventually, this seems like a bad implementation by Apple, and I don't know how to report issues efficiently to them.
